version: '3.9'

services:

  server:
    image: server-image
    container_name: server
    volumes:
      - .:/link_shortening:cached
    ports:
      - 8080:8080
    depends_on:
      - db
    
  client:
    image: client-image
    container_name: client
    volumes:
      - .:/link_shortening:cached
    ports:
      - 8081:8081
    environment:
      PORT: server:8080  
    depends_on:
      - server
    
  db:
    restart: always
    image: postgres:latest
    container_name: link_shortening-db
    volumes:
      - ./database:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5436:5432
    healthcheck:
      test: "exit 0"      
    